create table if not exists refresh_token_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(128) not null,
    expires_at timestamp not null,
    revoked_at timestamp null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    last_used_at timestamp null,
    replaced_by_session_id bigint null,
    user_agent varchar(512) null,
    ip_address varchar(64) null,
    constraint fk_refresh_token_sessions_user
        foreign key (user_id) references users(id),
    constraint uq_refresh_token_sessions_token_hash
        unique (token_hash)
);

create index if not exists idx_refresh_token_sessions_user_id
    on refresh_token_sessions(user_id);

create index if not exists idx_refresh_token_sessions_expires_at
    on refresh_token_sessions(expires_at);

select setval(
    pg_get_serial_sequence('refresh_token_sessions', 'id'),
    greatest((select coalesce(max(id), 0) from refresh_token_sessions), 1)
);
