create table if not exists planned_entries (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    direction varchar(20) not null,
    description varchar(255) not null,
    category_id bigint not null,
    subcategory_id bigint,
    expected_amount numeric(15,2) not null,
    actual_amount numeric(15,2),
    amount_behavior varchar(20) not null,
    due_date date not null,
    status varchar(20) not null default 'OPEN',
    default_account_id bigint,
    settled_account_id bigint,
    settled_at timestamp,
    movement_id bigint,
    group_id uuid,
    origin_type varchar(20) not null default 'SINGLE',
    notes varchar(2000),
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_planned_entries_workspace
        foreign key (workspace_id) references workspaces(id),
    constraint fk_planned_entries_category
        foreign key (category_id) references categories(id),
    constraint fk_planned_entries_subcategory
        foreign key (subcategory_id) references sub_categories(id),
    constraint fk_planned_entries_default_account
        foreign key (default_account_id) references accounts(id),
    constraint fk_planned_entries_settled_account
        foreign key (settled_account_id) references accounts(id),
    constraint fk_planned_entries_movement
        foreign key (movement_id) references cash_movements(id),
    constraint planned_entries_direction_check
        check (direction in ('INCOME','EXPENSE')),
    constraint planned_entries_amount_behavior_check
        check (amount_behavior in ('FIXED','ESTIMATED')),
    constraint planned_entries_status_check
        check (status in ('OPEN','COMPLETED','CANCELED','OVERDUE')),
    constraint planned_entries_origin_type_check
        check (origin_type in ('SINGLE','BATCH_MANUAL'))
);

create index if not exists idx_planned_entries_workspace_direction_due_date
    on planned_entries(workspace_id, direction, due_date);

create index if not exists idx_planned_entries_workspace_direction_status_due_date
    on planned_entries(workspace_id, direction, status, due_date);

create index if not exists idx_planned_entries_group_id
    on planned_entries(group_id);

create index if not exists idx_planned_entries_workspace_id
    on planned_entries(workspace_id);

select setval(
    pg_get_serial_sequence('planned_entries', 'id'),
    greatest((select coalesce(max(id), 0) from planned_entries), 1)
);
