create table if not exists holidays (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    holiday_date date not null,
    scope varchar(20) not null,
    country_code varchar(5),
    state_code varchar(10),
    city_name varchar(120),
    workspace_id bigint,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_holidays_workspace
        foreign key (workspace_id) references workspaces(id),
    constraint holidays_scope_check
        check (scope in ('NATIONAL','STATE','CITY','WORKSPACE'))
);

create index if not exists idx_holidays_holiday_date
    on holidays(holiday_date);

create index if not exists idx_holidays_scope
    on holidays(scope);

create index if not exists idx_holidays_workspace_id
    on holidays(workspace_id);

create unique index if not exists uk_holidays_scope_target_date
    on holidays (
        holiday_date,
        scope,
        coalesce(country_code, ''),
        coalesce(state_code, ''),
        coalesce(city_name, ''),
        coalesce(workspace_id, -1)
    );

insert into holidays (
    name,
    holiday_date,
    scope,
    country_code,
    active,
    created_at,
    updated_at
)
select v.name,
       v.holiday_date,
       'NATIONAL',
       'BR',
       true,
       now(),
       now()
from (
    values
        ('Confraternização Universal', date '2026-01-01'),
        ('Paixão de Cristo', date '2026-04-03'),
        ('Tiradentes', date '2026-04-21'),
        ('Dia do Trabalho', date '2026-05-01'),
        ('Independência do Brasil', date '2026-09-07'),
        ('Nossa Senhora Aparecida', date '2026-10-12'),
        ('Finados', date '2026-11-02'),
        ('Proclamação da República', date '2026-11-15'),
        ('Dia Nacional de Zumbi e da Consciência Negra', date '2026-11-20'),
        ('Natal', date '2026-12-25'),

        ('Confraternização Universal', date '2027-01-01'),
        ('Paixão de Cristo', date '2027-03-26'),
        ('Tiradentes', date '2027-04-21'),
        ('Dia do Trabalho', date '2027-05-01'),
        ('Independência do Brasil', date '2027-09-07'),
        ('Nossa Senhora Aparecida', date '2027-10-12'),
        ('Finados', date '2027-11-02'),
        ('Proclamação da República', date '2027-11-15'),
        ('Dia Nacional de Zumbi e da Consciência Negra', date '2027-11-20'),
        ('Natal', date '2027-12-25'),

        ('Confraternização Universal', date '2028-01-01'),
        ('Paixão de Cristo', date '2028-04-14'),
        ('Tiradentes', date '2028-04-21'),
        ('Dia do Trabalho', date '2028-05-01'),
        ('Independência do Brasil', date '2028-09-07'),
        ('Nossa Senhora Aparecida', date '2028-10-12'),
        ('Finados', date '2028-11-02'),
        ('Proclamação da República', date '2028-11-15'),
        ('Dia Nacional de Zumbi e da Consciência Negra', date '2028-11-20'),
        ('Natal', date '2028-12-25'),

        ('Confraternização Universal', date '2029-01-01'),
        ('Paixão de Cristo', date '2029-03-30'),
        ('Tiradentes', date '2029-04-21'),
        ('Dia do Trabalho', date '2029-05-01'),
        ('Independência do Brasil', date '2029-09-07'),
        ('Nossa Senhora Aparecida', date '2029-10-12'),
        ('Finados', date '2029-11-02'),
        ('Proclamação da República', date '2029-11-15'),
        ('Dia Nacional de Zumbi e da Consciência Negra', date '2029-11-20'),
        ('Natal', date '2029-12-25'),

        ('Confraternização Universal', date '2030-01-01'),
        ('Paixão de Cristo', date '2030-04-19'),
        ('Tiradentes', date '2030-04-21'),
        ('Dia do Trabalho', date '2030-05-01'),
        ('Independência do Brasil', date '2030-09-07'),
        ('Nossa Senhora Aparecida', date '2030-10-12'),
        ('Finados', date '2030-11-02'),
        ('Proclamação da República', date '2030-11-15'),
        ('Dia Nacional de Zumbi e da Consciência Negra', date '2030-11-20'),
        ('Natal', date '2030-12-25')
) as v(name, holiday_date)
where not exists (
    select 1
    from holidays h
    where h.holiday_date = v.holiday_date
      and h.scope = 'NATIONAL'
      and coalesce(h.country_code, '') = 'BR'
);

select setval(
    pg_get_serial_sequence('holidays', 'id'),
    greatest((select coalesce(max(id), 0) from holidays), 1)
);
