-- Credit card domain restructure:
-- - normalize credit_cards for current API contract
-- - evolve credit_card_invoices for year/month reference and invoice totals
-- - create credit_card_expenses and credit_card_invoice_payments

alter table credit_cards
    alter column credit_limit drop not null;

alter table credit_cards
    alter column limit_amount drop not null;

alter table credit_cards
    add column if not exists notes varchar(1000);

alter table credit_cards
    drop constraint if exists credit_cards_closing_day_check;

alter table credit_cards
    drop constraint if exists credit_cards_due_day_check;

alter table credit_cards
    add constraint credit_cards_closing_day_check check (closing_day between 1 and 31);

alter table credit_cards
    add constraint credit_cards_due_day_check check (due_day between 1 and 31);

alter table credit_card_invoices
    add column if not exists reference_year integer;

alter table credit_card_invoices
    add column if not exists reference_month_int integer;

update credit_card_invoices
set reference_year = cast(split_part(reference_month, '-', 1) as integer)
where reference_year is null
  and reference_month is not null
  and reference_month like '____-__';

update credit_card_invoices
set reference_month_int = cast(split_part(reference_month, '-', 2) as integer)
where reference_month_int is null
  and reference_month is not null
  and reference_month like '____-__';

update credit_card_invoices
set reference_year = extract(year from coalesce(due_date, closing_date, current_date))::integer
where reference_year is null;

update credit_card_invoices
set reference_month_int = extract(month from coalesce(due_date, closing_date, current_date))::integer
where reference_month_int is null;

alter table credit_card_invoices
    alter column reference_year set not null;

alter table credit_card_invoices
    alter column reference_month_int set not null;

alter table credit_card_invoices
    drop constraint if exists uk_credit_card_invoice_reference;

alter table credit_card_invoices
    rename column reference_month to reference_month_label;

alter table credit_card_invoices
    rename column reference_month_int to reference_month;

alter table credit_card_invoices
    add column if not exists period_start date;

alter table credit_card_invoices
    add column if not exists period_end date;

alter table credit_card_invoices
    add column if not exists purchases_amount numeric(15,2) not null default 0;

alter table credit_card_invoices
    add column if not exists previous_balance numeric(15,2) not null default 0;

alter table credit_card_invoices
    add column if not exists revolving_interest numeric(15,2) not null default 0;

alter table credit_card_invoices
    add column if not exists late_fee numeric(15,2) not null default 0;

alter table credit_card_invoices
    add column if not exists other_charges numeric(15,2) not null default 0;

alter table credit_card_invoices
    add column if not exists remaining_amount numeric(15,2) not null default 0;

update credit_card_invoices
set purchases_amount = coalesce(total_amount, 0)
where purchases_amount = 0 and total_amount is not null;

update credit_card_invoices
set remaining_amount = greatest(coalesce(total_amount, 0) - coalesce(paid_amount, 0), 0)
where remaining_amount = 0;

alter table credit_card_invoices
    add constraint uk_credit_card_invoice_reference unique (credit_card_id, reference_year, reference_month);

drop index if exists idx_credit_card_invoices_reference_month;
create index if not exists idx_credit_card_invoices_reference on credit_card_invoices(credit_card_id, reference_year, reference_month);

create table if not exists credit_card_expenses (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    credit_card_id bigint not null,
    invoice_id bigint,
    description varchar(255) not null,
    purchase_date date not null,
    category_id bigint not null,
    subcategory_id bigint not null,
    amount numeric(15,2) not null,
    installment_number integer,
    installment_count integer,
    installment_group_id uuid,
    notes varchar(1000),
    status varchar(20) not null default 'OPEN',
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_credit_card_expenses_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_credit_card_expenses_credit_card foreign key (credit_card_id) references credit_cards(id),
    constraint fk_credit_card_expenses_invoice foreign key (invoice_id) references credit_card_invoices(id),
    constraint fk_credit_card_expenses_category foreign key (category_id) references categories(id),
    constraint fk_credit_card_expenses_subcategory foreign key (subcategory_id) references sub_categories(id),
    constraint credit_card_expenses_status_check check (status in ('OPEN','CANCELED'))
);

create index if not exists idx_credit_card_expenses_workspace_id on credit_card_expenses(workspace_id);
create index if not exists idx_credit_card_expenses_credit_card_id on credit_card_expenses(credit_card_id);
create index if not exists idx_credit_card_expenses_invoice_id on credit_card_expenses(invoice_id);
create index if not exists idx_credit_card_expenses_purchase_date on credit_card_expenses(purchase_date);

create table if not exists credit_card_invoice_payments (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    invoice_id bigint not null,
    account_id bigint not null,
    payment_date date not null,
    amount numeric(15,2) not null,
    notes varchar(1000),
    movement_id bigint,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_credit_card_invoice_payments_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_credit_card_invoice_payments_invoice foreign key (invoice_id) references credit_card_invoices(id),
    constraint fk_credit_card_invoice_payments_account foreign key (account_id) references accounts(id),
    constraint fk_credit_card_invoice_payments_movement foreign key (movement_id) references cash_movements(id)
);

create index if not exists idx_credit_card_invoice_payments_workspace_id on credit_card_invoice_payments(workspace_id);
create index if not exists idx_credit_card_invoice_payments_invoice_id on credit_card_invoice_payments(invoice_id);
