create table accounts (
  id bigint generated by default as identity primary key,
  name varchar(255) not null unique,
  account_type varchar(50) not null,
  initial_balance numeric(15,2) not null,
  current_balance numeric(15,2) not null default 0,
  balance_updated_at timestamp,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint accounts_account_type_check
    check (account_type in ('CHECKING','CREDIT_CARD','CASH','INVESTMENT','SAVING','BENEFIT_CARD'))
);

create index idx_accounts_account_type on accounts(account_type);
create index idx_accounts_active on accounts(active);
