create table categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  movement_type varchar(50) not null,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint uk_category_name unique (name),
  constraint categories_movement_type_check
    check (movement_type in ('INCOME','EXPENSE'))
);

create index idx_categories_movement_type on categories(movement_type);
