create table cash_movements (
  id bigint generated by default as identity primary key,
  amount numeric(15,2) not null check (amount > 0),
  movement_type varchar(50) not null,
  payment_method varchar(50) not null,
  account_id bigint not null,
  category_id bigint not null,
  occurred_at date not null,
  reference_month date not null,
  description varchar(255),
  notes varchar(255),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,

  constraint cash_movements_movement_type_check
    check (movement_type in ('INCOME','EXPENSE')),

  constraint cash_movements_payment_method_check
    check (payment_method in ('CREDIT_CARD','DEBIT_CARD','DEBIT','PIX','BOLETO','CASH','TRANSFER','VA')),

  constraint fk_cash_account
    foreign key (account_id) references accounts(id),

  constraint fk_cash_category
    foreign key (category_id) references categories(id)
);

create index idx_cash_movements_account_id on cash_movements(account_id);
create index idx_cash_movements_category_id on cash_movements(category_id);
create index idx_cash_movements_occurred_at on cash_movements(occurred_at);
create index idx_cash_movements_reference_month on cash_movements(reference_month);
create index idx_cash_movements_movement_type on cash_movements(movement_type);
create index idx_cash_movements_account_ref_month on cash_movements(account_id, reference_month);

