-- Workspace and audit migration for existing core tables

-- 1) Identity tables
create table if not exists users (
    id bigint generated by default as identity primary key,
    full_name varchar(120) not null,
    email varchar(150) not null,
    password varchar(255) not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint uk_users_email unique (email)
);

create table if not exists workspaces (
    id bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table if not exists workspace_users (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    user_id bigint not null,
    role varchar(30),
    constraint uk_workspace_users_workspace_user unique (workspace_id, user_id),
    constraint fk_workspace_users_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_workspace_users_user foreign key (user_id) references users(id)
);

-- Seed for current mock services (userId=1, workspaceId=1)
insert into users (id, full_name, email, password, active, created_at, updated_at, created_by_user_id, updated_by_user_id)
values (1, 'Usuario Padrao', 'admin@meufluxo.local', 'mock-password', true, now(), now(), 1, 1)
on conflict (id) do nothing;

insert into workspaces (id, name)
values (1, 'Workspace Padrao')
on conflict (id) do nothing;

insert into workspace_users (workspace_id, user_id, role)
values (1, 1, 'OWNER')
on conflict (workspace_id, user_id) do nothing;

select setval(pg_get_serial_sequence('users', 'id'), greatest((select coalesce(max(id), 0) from users), 1));
select setval(pg_get_serial_sequence('workspaces', 'id'), greatest((select coalesce(max(id), 0) from workspaces), 1));
select setval(pg_get_serial_sequence('workspace_users', 'id'), greatest((select coalesce(max(id), 0) from workspace_users), 1));

-- 2) Accounts
alter table accounts add column if not exists workspace_id bigint;
alter table accounts add column if not exists created_by_user_id bigint;
alter table accounts add column if not exists updated_by_user_id bigint;

update accounts
set workspace_id = 1
where workspace_id is null;

update accounts
set created_by_user_id = coalesce(created_by_user_id, 1),
    updated_by_user_id = coalesce(updated_by_user_id, 1)
where created_by_user_id is null
   or updated_by_user_id is null;

alter table accounts alter column workspace_id set not null;

alter table accounts drop constraint if exists uk_account_user_name;
alter table accounts drop constraint if exists accounts_name_key;

alter table accounts
    add constraint fk_accounts_workspace
    foreign key (workspace_id) references workspaces(id);

alter table accounts
    add constraint uk_account_workspace_name
    unique (workspace_id, name);

create index if not exists idx_accounts_workspace_id on accounts(workspace_id);

-- 3) Categories
alter table categories add column if not exists workspace_id bigint;
alter table categories add column if not exists created_by_user_id bigint;
alter table categories add column if not exists updated_by_user_id bigint;

update categories
set workspace_id = 1
where workspace_id is null;

update categories
set created_by_user_id = coalesce(created_by_user_id, 1),
    updated_by_user_id = coalesce(updated_by_user_id, 1)
where created_by_user_id is null
   or updated_by_user_id is null;

alter table categories alter column workspace_id set not null;

alter table categories drop constraint if exists uk_category_name;
alter table categories drop constraint if exists uk_category_user_name;

alter table categories
    add constraint fk_categories_workspace
    foreign key (workspace_id) references workspaces(id);

alter table categories
    add constraint uk_category_workspace_name
    unique (workspace_id, name);

create index if not exists idx_categories_workspace_id on categories(workspace_id);

-- 4) Subcategories (new)
create table if not exists sub_categories (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    category_id bigint not null,
    workspace_id bigint not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_sub_categories_category foreign key (category_id) references categories(id),
    constraint fk_sub_categories_workspace foreign key (workspace_id) references workspaces(id),
    constraint uk_subcategory_workspace_category_name unique (workspace_id, category_id, name)
);

create index if not exists idx_sub_categories_workspace_id on sub_categories(workspace_id);
create index if not exists idx_sub_categories_category_id on sub_categories(category_id);

-- backfill one subcategory per category to preserve existing records
insert into sub_categories (name, category_id, workspace_id, active, created_at, updated_at, created_by_user_id, updated_by_user_id)
select c.name,
       c.id,
       c.workspace_id,
       c.active,
       c.created_at,
       c.updated_at,
       coalesce(c.created_by_user_id, 1),
       coalesce(c.updated_by_user_id, 1)
from categories c
where not exists (
    select 1
    from sub_categories s
    where s.category_id = c.id
      and s.workspace_id = c.workspace_id
      and s.name = c.name
);

-- 5) Cash movements
alter table cash_movements add column if not exists workspace_id bigint;
alter table cash_movements add column if not exists subcategory_id bigint;
alter table cash_movements add column if not exists created_by bigint;
alter table cash_movements add column if not exists credit_card_invoice_id bigint;
alter table cash_movements add column if not exists created_by_user_id bigint;
alter table cash_movements add column if not exists updated_by_user_id bigint;

update cash_movements cm
set workspace_id = a.workspace_id
from accounts a
where cm.account_id = a.id
  and cm.workspace_id is null;

update cash_movements
set workspace_id = 1
where workspace_id is null;

update cash_movements cm
set subcategory_id = s.id
from sub_categories s
where cm.subcategory_id is null
  and cm.category_id = s.category_id
  and cm.workspace_id = s.workspace_id;

update cash_movements
set created_by_user_id = coalesce(created_by_user_id, 1),
    updated_by_user_id = coalesce(updated_by_user_id, 1)
where created_by_user_id is null
   or updated_by_user_id is null;

alter table cash_movements alter column workspace_id set not null;
alter table cash_movements alter column subcategory_id set not null;

alter table cash_movements drop constraint if exists fk_cash_category;
alter table cash_movements drop column if exists category_id;

alter table cash_movements drop constraint if exists cash_movements_payment_method_check;
alter table cash_movements
    add constraint cash_movements_payment_method_check
    check (payment_method in ('PIX','DEBIT','CASH','TRANSFER','BOLETO','VA','INVOICE_CREDIT_CARD','CREDIT_CARD','DEBIT_CARD'));

alter table cash_movements
    add constraint fk_cash_workspace
    foreign key (workspace_id) references workspaces(id);

alter table cash_movements
    add constraint fk_cash_subcategory
    foreign key (subcategory_id) references sub_categories(id);

alter table cash_movements
    add constraint fk_cash_created_by_workspace_user
    foreign key (created_by) references workspace_users(id);

create index if not exists idx_cash_movements_workspace_id on cash_movements(workspace_id);
create index if not exists idx_cash_movements_subcategory_id on cash_movements(subcategory_id);
