-- Create new domain tables required by current entities

create table if not exists credit_cards (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    name varchar(255) not null,
    last_four_digits varchar(4),
    credit_limit numeric(15,2) not null,
    closing_day integer not null,
    due_day integer not null,
    annual_fee_enabled boolean not null default false,
    annual_fee_amount numeric(15,2),
    brand_card varchar(50) not null,
    limit_amount numeric(15,2) not null,
    annual_fee_waiver_threshold numeric(15,2),
    default_payment_account_id bigint,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_credit_cards_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_credit_cards_default_payment_account foreign key (default_payment_account_id) references accounts(id),
    constraint credit_cards_brand_card_check check (brand_card in ('VISA','MASTERCARD'))
);

create index if not exists idx_credit_cards_workspace_id on credit_cards(workspace_id);

create table if not exists credit_card_invoices (
    id bigint generated by default as identity primary key,
    reference_month varchar(7) not null,
    closing_date date not null,
    due_date date not null,
    adjusted_due_date date,
    total_amount numeric(15,2) not null default 0,
    paid_amount numeric(15,2) not null default 0,
    status varchar(30) not null default 'OPEN',
    paid_at date,
    credit_card_id bigint not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint uk_credit_card_invoice_reference unique (credit_card_id, reference_month),
    constraint fk_credit_card_invoices_credit_card foreign key (credit_card_id) references credit_cards(id),
    constraint credit_card_invoices_status_check check (status in ('OPEN','CLOSED','PAID','PARTIALLY_PAID','OVERDUE'))
);

create index if not exists idx_credit_card_invoices_credit_card_id on credit_card_invoices(credit_card_id);
create index if not exists idx_credit_card_invoices_reference_month on credit_card_invoices(reference_month);

create table if not exists credit_card_transactions (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    amount numeric(15,2) not null,
    description varchar(255) not null,
    purchase_date date not null,
    installments_count integer not null default 1,
    status varchar(20) not null default 'ACTIVE',
    credit_card_id bigint not null,
    category_id bigint not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_credit_card_transactions_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_credit_card_transactions_credit_card foreign key (credit_card_id) references credit_cards(id),
    constraint fk_credit_card_transactions_category foreign key (category_id) references categories(id),
    constraint credit_card_transactions_status_check check (status in ('ACTIVE','CANCELED','REVERSED'))
);

create index if not exists idx_credit_card_transactions_workspace_id on credit_card_transactions(workspace_id);
create index if not exists idx_credit_card_transactions_credit_card_id on credit_card_transactions(credit_card_id);
create index if not exists idx_credit_card_transactions_category_id on credit_card_transactions(category_id);

create table if not exists credit_card_installments (
    id bigint generated by default as identity primary key,
    installment_number integer not null,
    amount numeric(15,2) not null,
    competence_date date not null,
    reference_month varchar(7) not null,
    status varchar(20) not null default 'OPEN',
    transaction_id bigint not null,
    invoice_id bigint not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint uk_transaction_installment_number unique (transaction_id, installment_number),
    constraint fk_credit_card_installments_transaction foreign key (transaction_id) references credit_card_transactions(id),
    constraint fk_credit_card_installments_invoice foreign key (invoice_id) references credit_card_invoices(id),
    constraint credit_card_installments_status_check check (status in ('OPEN','INVOICED','PAID','CANCELED'))
);

create index if not exists idx_credit_card_installments_transaction_id on credit_card_installments(transaction_id);
create index if not exists idx_credit_card_installments_invoice_id on credit_card_installments(invoice_id);

create table if not exists financial_projections (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    amount numeric(15,2) not null,
    description varchar(255),
    category_id_id bigint not null,
    account_id_id bigint not null,
    due_date timestamp not null,
    recurring boolean not null default false,
    recurrence_type varchar(20),
    projection_status varchar(20) not null,
    notes varchar(500),
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_financial_projections_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_financial_projections_category foreign key (category_id_id) references categories(id),
    constraint fk_financial_projections_account foreign key (account_id_id) references accounts(id),
    constraint financial_projections_recurrence_type_check check (recurrence_type in ('WEEKLY','BIWEEKLY','MONTHLY','BIMONTHLY','QUARTERLY','YEARLY')),
    constraint financial_projections_status_check check (projection_status in ('PENDING','PAID','CANCELED'))
);

create index if not exists idx_financial_projections_workspace_id on financial_projections(workspace_id);

create table if not exists invoices (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    credit_card_id bigint not null,
    reference_month integer not null,
    reference_year integer not null,
    amount numeric(15,2) not null,
    status varchar(30) not null default 'OPEN',
    due_date date,
    paid_at date,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_invoices_workspace foreign key (workspace_id) references workspaces(id),
    constraint fk_invoices_credit_card foreign key (credit_card_id) references credit_cards(id),
    constraint invoices_status_check check (status in ('OPEN','CLOSED','PAID','PARTIALLY_PAID','OVERDUE'))
);

create index if not exists idx_invoices_workspace_id on invoices(workspace_id);
create index if not exists idx_invoices_credit_card_id on invoices(credit_card_id);

alter table cash_movements
    add constraint fk_cash_credit_card_invoice
    foreign key (credit_card_invoice_id) references credit_card_invoices(id);
