alter table workspaces
    add column if not exists description varchar(255);

alter table workspaces
    add column if not exists active boolean not null default true;

alter table workspaces
    add column if not exists created_at timestamp not null default current_timestamp;

alter table workspaces
    add column if not exists updated_at timestamp not null default current_timestamp;

alter table workspaces
    add column if not exists created_by_user_id bigint;

alter table workspaces
    add column if not exists updated_by_user_id bigint;

alter table workspace_users
    add column if not exists enabled boolean not null default true;

alter table workspace_users
    add column if not exists active boolean not null default true;

alter table workspace_users
    add column if not exists created_at timestamp not null default current_timestamp;

alter table workspace_users
    add column if not exists updated_at timestamp not null default current_timestamp;

alter table workspace_users
    add column if not exists created_by_user_id bigint;

alter table workspace_users
    add column if not exists updated_by_user_id bigint;

create table if not exists user_preferences (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    language varchar(10) not null,
    theme varchar(10) not null,
    currency varchar(10) not null,
    date_format varchar(20) not null,
    timezone varchar(60) not null,
    active_workspace_id bigint,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by_user_id bigint,
    updated_by_user_id bigint,
    constraint fk_user_preferences_user foreign key (user_id) references users(id),
    constraint fk_user_preferences_active_workspace foreign key (active_workspace_id) references workspaces(id)
);

insert into user_preferences (
    user_id,
    language,
    theme,
    currency,
    date_format,
    timezone,
    active_workspace_id,
    active,
    created_at,
    updated_at
)
select u.id,
       'pt-BR',
       'dark',
       'BRL',
       'dd/MM/yyyy',
       'America/Sao_Paulo',
       (
           select wu.workspace_id
           from workspace_users wu
           where wu.user_id = u.id
           order by wu.id
           limit 1
       ),
       true,
       now(),
       now()
from users u
where not exists (
    select 1
    from user_preferences up
    where up.user_id = u.id
);

create index if not exists idx_user_preferences_user_id on user_preferences(user_id);
create index if not exists idx_user_preferences_active_workspace_id on user_preferences(active_workspace_id);

select setval(pg_get_serial_sequence('user_preferences', 'id'), greatest((select coalesce(max(id), 0) from user_preferences), 1));
