create table if not exists workspace_sync_states (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null unique,
    categories_version bigint not null default 1,
    accounts_version bigint not null default 1,
    credit_cards_version bigint not null default 1,
    updated_at timestamp not null default current_timestamp,
    constraint fk_workspace_sync_states_workspace
        foreign key (workspace_id) references workspaces(id)
);

insert into workspace_sync_states (
    workspace_id,
    categories_version,
    accounts_version,
    credit_cards_version,
    updated_at
)
select w.id, 1, 1, 1, now()
from workspaces w
where not exists (
    select 1
    from workspace_sync_states sync_state
    where sync_state.workspace_id = w.id
);

create index if not exists idx_workspace_sync_states_workspace_id
    on workspace_sync_states(workspace_id);

select setval(
    pg_get_serial_sequence('workspace_sync_states', 'id'),
    greatest((select coalesce(max(id), 0) from workspace_sync_states), 1)
);
